import React, { useState, useEffect } from 'react';
import {
  Box,
  Typography,
  Button,
  Tab,
  Tabs,
  Paper,
  IconButton,
  Tooltip,
  Alert,
  CircularProgress,
  Chip,
  Card,
  CardContent,
  Divider
} from '@mui/material';
import { alpha } from '@mui/material/styles';
import {
  Code as CodeIcon,
  ContentCopy as CopyIcon,
  Download as DownloadIcon,
  Refresh as RefreshIcon,
  PlayArrow as RunIcon,
  CheckCircle as CheckIcon,
  Error as ErrorIcon,
  Warning as WarningIcon
} from '@mui/icons-material';

import { WorkflowV2Config } from '../../types/workflow-v2';

// 模拟代码生成（实际应该调用后端API）
function generatePythonCode(config: WorkflowV2Config): string {
  const className = config.name.replace(/\s+/g, '') + 'Workflow';
  
  return `import asyncio
from typing import Dict, Any
import logging

logger = logging.getLogger(__name__)

class ${className}:
    """
    ${config.description || '工作流描述'}
    
    Generated by ZZDSJ Carbon Agent Service
    Based on SiliconFlow API
    """
    
    description: str = "${config.description || ''}"
    
    def __init__(self):
        self.agents = {}
        self.setup_agents()
    
    def setup_agents(self):
        """初始化智能体"""
        ${config.components.agents.map(agent => `
        # ${agent.name}
        self.agents["${agent.id}"] = {
            "name": "${agent.name}",
            "model": "${agent.model_name}",
            "instructions": """${agent.instructions}""",
            "tools": ${JSON.stringify(agent.tools || [])},
            "temperature": ${agent.temperature || 0.7},
            "max_tokens": ${agent.max_tokens || 4096}
        }`).join('')}
    
    async def create_${config.components.agents[0]?.id || 'agent'}(self):
        """创建智能体实例"""
        from app.adapters.siliconflow_adapter import siliconflow_adapter
        
        agent_config = self.agents["${config.components.agents[0]?.id || 'agent'}"]
        return await siliconflow_adapter.create_agent(
            name=agent_config["name"],
            model_name=agent_config["model"],
            instructions=agent_config["instructions"],
            tools=agent_config["tools"],
            temperature=agent_config["temperature"],
            max_tokens=agent_config["max_tokens"]
        )
    
    async def run(self, ${config.logic.variables ? Object.keys(config.logic.variables).join(': str, ') + ': str' : 'message: str'}) -> Dict[str, Any]:
        """执行工作流主逻辑"""
        logger.info(f"开始执行工作流: {${Object.keys(config.logic.variables || {message: 'string'})[0] || 'message'}}")
        results = {}
        
        try:
            ${config.logic.steps.map((step, index) => `
            # 执行步骤${index + 1}: ${step.name}
            logger.info(f"执行步骤: ${step.name}")
            ${step.component_ref ? `${step.component_ref}_instance = await self.create_${step.component_ref}()
            step${index + 1}_result = await ${step.component_ref}_instance.run(${Object.keys(config.logic.variables || {message: 'string'})[0] || 'message'})
            results["${step.id}"] = step${index + 1}_result` : '# 步骤配置不完整'}
            `).join('')}
            
            # 返回最终结果
            final_result = results.get("${config.logic.steps[config.logic.steps.length - 1]?.id || 'final'}", {})
            
            return {
                "status": "completed",
                "result": final_result.get("content", str(final_result)) if isinstance(final_result, dict) else str(final_result),
                "steps_results": results,
                "workflow_name": "${config.name}",
                "execution_time": "{{execution_time}}"
            }
            
        except Exception as e:
            logger.error(f"工作流执行失败: {str(e)}")
            return {
                "status": "failed",
                "error": str(e),
                "steps_results": results,
                "workflow_name": "${config.name}"
            }

# 工作流实例
${config.name.toLowerCase().replace(/\s+/g, '_')}_workflow = ${className}()

# 测试函数
async def test_workflow():
    """测试工作流执行"""
    test_input = "${Object.keys(config.logic.variables || {}).includes('message') ? '你好，请帮我分析一下数据' : '测试输入'}"
    result = await ${config.name.toLowerCase().replace(/\s+/g, '_')}_workflow.run(${config.logic.variables ? Object.keys(config.logic.variables).map(() => 'test_input').join(', ') : 'test_input'})
    print(f"执行结果: {result}")
    return result

if __name__ == "__main__":
    asyncio.run(test_workflow())`;
}

// 代码验证结果
interface CodeValidationResult {
  syntax_valid: boolean;
  siliconflow_compliant: boolean;
  warnings: string[];
  errors: string[];
}

// 模拟代码验证
function validateCode(code: string): CodeValidationResult {
  const warnings: string[] = [];
  const errors: string[] = [];
  
  // 基础语法检查
  if (!code.includes('async def run')) {
    errors.push('缺少异步run方法定义');
  }
  
  if (!code.includes('siliconflow_adapter')) {
    warnings.push('未使用硅基流动适配器');
  }
  
  if (code.includes('# 步骤配置不完整')) {
    warnings.push('存在配置不完整的步骤');
  }
  
  if (!code.includes('try:') || !code.includes('except:')) {
    warnings.push('建议添加错误处理机制');
  }
  
  return {
    syntax_valid: errors.length === 0,
    siliconflow_compliant: !warnings.some(w => w.includes('硅基流动')),
    warnings,
    errors
  };
}

interface CodePreviewPanelProps {
  config: WorkflowV2Config;
  onExecuteTest?: () => void;
}

export default function CodePreviewPanel({ config, onExecuteTest }: CodePreviewPanelProps) {
  const [activeTab, setActiveTab] = useState(0);
  const [generatedCode, setGeneratedCode] = useState<string>('');
  const [validation, setValidation] = useState<CodeValidationResult | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [copySuccess, setCopySuccess] = useState(false);

  // 生成代码
  useEffect(() => {
    if (config && config.name) {
      setIsGenerating(true);
      // 模拟API调用延迟
      setTimeout(() => {
        const code = generatePythonCode(config);
        setGeneratedCode(code);
        setValidation(validateCode(code));
        setIsGenerating(false);
      }, 500);
    }
  }, [config]);

  // 复制代码到剪贴板
  const handleCopyCode = async () => {
    try {
      await navigator.clipboard.writeText(generatedCode);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (err) {
      console.error('复制失败:', err);
    }
  };

  // 下载代码文件
  const handleDownloadCode = () => {
    const blob = new Blob([generatedCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${config.name.toLowerCase().replace(/\s+/g, '_')}_workflow.py`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // 重新生成代码
  const handleRegenerateCode = () => {
    setIsGenerating(true);
    setTimeout(() => {
      const code = generatePythonCode(config);
      setGeneratedCode(code);
      setValidation(validateCode(code));
      setIsGenerating(false);
    }, 500);
  };

  return (
    <Box sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      {/* 头部 */}
      <Box sx={{ 
        p: 4, 
        background: 'linear-gradient(135deg, rgba(16, 185, 129, 0.1) 0%, rgba(5, 150, 105, 0.05) 100%)',
        borderBottom: '1px solid',
        borderColor: alpha('#10b981', 0.2)
      }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <Box>
            <Typography variant="h5" gutterBottom sx={{
              background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
              backgroundClip: 'text',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              fontWeight: 700,
              fontSize: '1.5rem'
            }}>
              💻 智能代码预览
            </Typography>
            <Typography variant="body2" sx={{ 
              color: '#64748b',
              fontSize: '0.95rem'
            }}>
              实时生成的Python工作流代码，支持硅基流动API
            </Typography>
          </Box>
          <Box sx={{ display: 'flex', gap: 1 }}>
            <Tooltip title={copySuccess ? "已复制!" : "复制代码"}>
              <IconButton 
                onClick={handleCopyCode} 
                disabled={!generatedCode}
                sx={{
                  background: copySuccess ? 'linear-gradient(135deg, #10b981 0%, #059669 100%)' : alpha('#10b981', 0.1),
                  color: copySuccess ? 'white' : '#10b981',
                  '&:hover': {
                    background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
                    color: 'white',
                    transform: 'scale(1.05)'
                  },
                  transition: 'all 0.2s ease'
                }}
              >
                {copySuccess ? <CheckIcon /> : <CopyIcon />}
              </IconButton>
            </Tooltip>
            <Tooltip title="下载代码">
              <IconButton 
                onClick={handleDownloadCode} 
                disabled={!generatedCode}
                sx={{
                  background: alpha('#3b82f6', 0.1),
                  color: '#3b82f6',
                  '&:hover': {
                    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
                    color: 'white',
                    transform: 'scale(1.05)'
                  },
                  transition: 'all 0.2s ease'
                }}
              >
                <DownloadIcon />
              </IconButton>
            </Tooltip>
            <Tooltip title="重新生成">
              <IconButton 
                onClick={handleRegenerateCode} 
                disabled={isGenerating}
                sx={{
                  background: alpha('#f59e0b', 0.1),
                  color: '#f59e0b',
                  '&:hover': {
                    background: 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
                    color: 'white',
                    transform: 'scale(1.05)'
                  },
                  transition: 'all 0.2s ease'
                }}
              >
                <RefreshIcon />
              </IconButton>
            </Tooltip>
            {onExecuteTest && (
              <Tooltip title="测试执行">
                <IconButton 
                  onClick={onExecuteTest} 
                  disabled={!generatedCode || !validation?.syntax_valid}
                  sx={{
                    background: alpha('#8b5cf6', 0.1),
                    color: '#8b5cf6',
                    '&:hover': {
                      background: 'linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)',
                      color: 'white',
                      transform: 'scale(1.05)'
                    },
                    transition: 'all 0.2s ease'
                  }}
                >
                  <RunIcon />
                </IconButton>
              </Tooltip>
            )}
          </Box>
        </Box>
      </Box>

      {/* 标签页 */}
      <Box sx={{ 
        borderBottom: '1px solid',
        borderColor: alpha('#e0e7ff', 0.6),
        background: alpha('#ffffff', 0.8)
      }}>
        <Tabs 
          value={activeTab} 
          onChange={(_, newValue) => setActiveTab(newValue)}
          sx={{
            '& .MuiTab-root': {
              color: '#64748b',
              fontWeight: 500,
              textTransform: 'none',
              minHeight: 48,
              '&:hover': {
                color: '#3b82f6',
                background: alpha('#3b82f6', 0.05)
              },
              '&.Mui-selected': {
                color: '#3b82f6',
                fontWeight: 600
              }
            },
            '& .MuiTabs-indicator': {
              background: 'linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%)',
              height: 3,
              borderRadius: '2px 2px 0 0'
            }
          }}
        >
          <Tab 
            icon={<CodeIcon sx={{ fontSize: 20 }} />} 
            label="Python代码" 
            iconPosition="start"
          />
          <Tab 
            icon={<CheckIcon sx={{ fontSize: 20 }} />} 
            label="验证结果" 
            iconPosition="start"
          />
          <Tab 
            icon={<RunIcon sx={{ fontSize: 20 }} />} 
            label="执行配置" 
            iconPosition="start"
          />
        </Tabs>
      </Box>

      {/* 内容区域 */}
      <Box sx={{ flex: 1, overflow: 'hidden' }}>
        {/* Python代码标签 */}
        {activeTab === 0 && (
          <Box sx={{ height: '100%', position: 'relative' }}>
            {isGenerating ? (
              <Box sx={{ 
                display: 'flex', 
                justifyContent: 'center', 
                alignItems: 'center', 
                height: '100%',
                flexDirection: 'column',
                gap: 2
              }}>
                <CircularProgress />
                <Typography variant="body2" color="text.secondary">
                  正在生成Python代码...
                </Typography>
              </Box>
            ) : (
              <Box sx={{ height: '100%', p: 3 }}>
                <Box sx={{
                  height: '100%',
                  background: 'linear-gradient(135deg, rgba(15, 23, 42, 0.95) 0%, rgba(30, 41, 59, 0.9) 100%)',
                  borderRadius: 2,
                  border: '1px solid',
                  borderColor: alpha('#334155', 0.5),
                  position: 'relative',
                  overflow: 'hidden',
                  boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)'
                }}>
                  {/* 终端顶部装饰 */}
                  <Box sx={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: 1,
                    p: 2,
                    background: alpha('#1e293b', 0.8),
                    borderBottom: '1px solid',
                    borderColor: alpha('#334155', 0.5)
                  }}>
                    <Box sx={{ width: 12, height: 12, borderRadius: '50%', bgcolor: '#ef4444' }} />
                    <Box sx={{ width: 12, height: 12, borderRadius: '50%', bgcolor: '#f59e0b' }} />
                    <Box sx={{ width: 12, height: 12, borderRadius: '50%', bgcolor: '#10b981' }} />
                    <Typography variant="caption" sx={{ 
                      color: '#94a3b8', 
                      ml: 2,
                      fontFamily: 'Monaco, Consolas, "Courier New", monospace'
                    }}>
                      workflow_v2.py
                    </Typography>
                  </Box>
                  <pre style={{
                    fontFamily: 'Monaco, Consolas, "SF Mono", "Fira Code", monospace',
                    fontSize: '13px',
                    lineHeight: 1.6,
                    margin: 0,
                    padding: '20px',
                    backgroundColor: 'transparent',
                    color: '#e2e8f0',
                    overflow: 'auto',
                    height: 'calc(100% - 60px)',
                    whiteSpace: 'pre-wrap',
                    wordBreak: 'break-word'
                  }}>
                    {generatedCode || `# 🚀 等待配置完成以生成智能体工作流代码
# 配置您的智能体和执行步骤，系统将自动生成
# 基于硅基流动API的Python工作流代码

print("🎯 准备就绪，开始您的AI编排之旅...")`}
                  </pre>
                </Box>
              </Box>
            )}
          </Box>
        )}

        {/* 验证结果标签 */}
        {activeTab === 1 && (
          <Box sx={{ p: 4, background: alpha('#f8fafc', 0.5) }}>
            {validation ? (
              <>
                <Box sx={{ display: 'flex', gap: 2, mb: 4 }}>
                  <Chip
                    icon={validation.syntax_valid ? <CheckIcon /> : <ErrorIcon />}
                    label={validation.syntax_valid ? "✅ 语法正确" : "❌ 语法错误"}
                    sx={{
                      background: validation.syntax_valid 
                        ? 'linear-gradient(135deg, #10b981 0%, #059669 100%)'
                        : 'linear-gradient(135deg, #ef4444 0%, #dc2626 100%)',
                      color: 'white',
                      fontWeight: 600,
                      px: 2,
                      py: 0.5,
                      '& .MuiChip-icon': { color: 'white' }
                    }}
                  />
                  <Chip
                    icon={validation.siliconflow_compliant ? <CheckIcon /> : <WarningIcon />}
                    label={validation.siliconflow_compliant ? "🚀 硅基流动兼容" : "⚠️ 需要优化"}
                    sx={{
                      background: validation.siliconflow_compliant 
                        ? 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)'
                        : 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
                      color: 'white',
                      fontWeight: 600,
                      px: 2,
                      py: 0.5,
                      '& .MuiChip-icon': { color: 'white' }
                    }}
                  />
                </Box>

                {validation.errors.length > 0 && (
                  <Alert 
                    severity="error" 
                    sx={{ 
                      mb: 3,
                      borderRadius: 2,
                      background: 'linear-gradient(135deg, rgba(254, 226, 226, 0.8) 0%, rgba(252, 165, 165, 0.3) 100%)',
                      border: '1px solid',
                      borderColor: alpha('#ef4444', 0.3)
                    }}
                  >
                    <Typography variant="subtitle2" gutterBottom sx={{ fontWeight: 600 }}>
                      🚨 发现错误
                    </Typography>
                    {validation.errors.map((error, index) => (
                      <Typography key={index} variant="body2" sx={{ 
                        color: '#7f1d1d',
                        display: 'flex',
                        alignItems: 'center',
                        gap: 1,
                        mb: 0.5
                      }}>
                        <span>•</span> {error}
                      </Typography>
                    ))}
                  </Alert>
                )}

                {validation.warnings.length > 0 && (
                  <Alert 
                    severity="warning" 
                    sx={{ 
                      mb: 3,
                      borderRadius: 2,
                      background: 'linear-gradient(135deg, rgba(254, 243, 199, 0.8) 0%, rgba(253, 230, 138, 0.3) 100%)',
                      border: '1px solid',
                      borderColor: alpha('#f59e0b', 0.3)
                    }}
                  >
                    <Typography variant="subtitle2" gutterBottom sx={{ fontWeight: 600 }}>
                      ⚠️ 发现警告
                    </Typography>
                    {validation.warnings.map((warning, index) => (
                      <Typography key={index} variant="body2" sx={{ 
                        color: '#92400e',
                        display: 'flex',
                        alignItems: 'center',
                        gap: 1,
                        mb: 0.5
                      }}>
                        <span>•</span> {warning}
                      </Typography>
                    ))}
                  </Alert>
                )}

                {validation.syntax_valid && validation.warnings.length === 0 && (
                  <Alert 
                    severity="success"
                    sx={{
                      borderRadius: 2,
                      background: 'linear-gradient(135deg, rgba(209, 250, 229, 0.8) 0%, rgba(167, 243, 208, 0.3) 100%)',
                      border: '1px solid',
                      borderColor: alpha('#10b981', 0.3)
                    }}
                  >
                    <Typography variant="subtitle2" gutterBottom sx={{ fontWeight: 600 }}>
                      🎉 验证通过
                    </Typography>
                    <Typography variant="body2" sx={{ color: '#065f46' }}>
                      代码语法正确，符合硅基流动API规范，可以正常执行。所有检查项目均已通过！
                    </Typography>
                  </Alert>
                )}
              </>
            ) : (
              <Box sx={{ 
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center',
                py: 6,
                gap: 2
              }}>
                <CircularProgress size={40} sx={{ color: '#3b82f6' }} />
                <Typography variant="body2" sx={{ color: '#64748b', textAlign: 'center' }}>
                  🔄 等待代码生成完成...
                </Typography>
              </Box>
            )}
          </Box>
        )}

        {/* 执行配置标签 */}
        {activeTab === 2 && (
          <Box sx={{ p: 3 }}>
            <Typography variant="h6" gutterBottom>执行环境配置</Typography>
            
            <Card sx={{ mb: 2 }}>
              <CardContent>
                <Typography variant="subtitle1" gutterBottom>基础配置</Typography>
                <Typography variant="body2">工作流名称: {config.name}</Typography>
                <Typography variant="body2">执行模式: {config.execution_mode}</Typography>
                <Typography variant="body2">最大并发: {config.logic.max_concurrent_steps}</Typography>
                <Typography variant="body2">超时时间: {config.logic.timeout} 秒</Typography>
              </CardContent>
            </Card>

            <Card sx={{ mb: 2 }}>
              <CardContent>
                <Typography variant="subtitle1" gutterBottom>依赖模块</Typography>
                <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                  <Chip label="asyncio" size="small" />
                  <Chip label="logging" size="small" />
                  <Chip label="siliconflow_adapter" size="small" />
                  {config.components.agents.some(a => a.tools?.includes('search')) && (
                    <Chip label="search_tools" size="small" />
                  )}
                  {config.components.agents.some(a => a.tools?.includes('calculator')) && (
                    <Chip label="calculator_tools" size="small" />
                  )}
                </Box>
              </CardContent>
            </Card>

            <Card>
              <CardContent>
                <Typography variant="subtitle1" gutterBottom>模型配置</Typography>
                {config.components.agents.map((agent) => (
                  <Box key={agent.id} sx={{ mb: 1 }}>
                    <Typography variant="body2">
                      <strong>{agent.name}:</strong> {agent.model_name}
                      {agent.tools && agent.tools.length > 0 && (
                        <span> (工具: {agent.tools.join(', ')})</span>
                      )}
                    </Typography>
                  </Box>
                ))}
              </CardContent>
            </Card>

            <Divider sx={{ my: 2 }} />

            <Alert severity="info">
              <Typography variant="subtitle2" gutterBottom>执行说明</Typography>
              <Typography variant="body2">
                1. 确保已安装必要的依赖模块<br/>
                2. 配置硅基流动API密钥<br/>
                3. 检查网络连接和权限设置<br/>
                4. 建议在测试环境中先行验证
              </Typography>
            </Alert>
          </Box>
        )}
      </Box>
    </Box>
  );
} 